### ISSUE TITLE
crashing after question

### ISSUE THREAD

**Issue by Aiki-bot51** [Gamegenorator/WogglAI-FuctionalScript#3]
![woggle question problem](https://user-images.githubusercontent.com/48476126/55075244-1570bc80-50c5-11e9-80c2-d28f7ceb102f.PNG)
what does this mean?

**Comment by Aiki-bot51** [comment]
use the link https://stackoverflow.com/questions/55382304/typeerror-object-of-type-map-has-no-len-on-woggle-v-1-2/55386176?noredirect=1
for references

**Comment by Gamegenorator** [comment]
@Aiki-bot51 Is there a reason you re-opened this question?

**Comment by Gamegenorator** [comment]
If you want to know how the problem was fixed, you can go to @Aiki-bot51 's Stack exchange question here: 
https://stackoverflow.com/questions/55382304/typeerror-object-of-type-map-has-no-len-on-woggle-v-1-2/55386176?noredirect=1
But if you don't need to know how and just want to get it working we have already updated the code, there is no need for further action on this proble,
